---
- name: Manage Arista EOS EVPN/VXLAN Configuration
  hosts: leaf-1a
  connection: local
  gather_facts: false
  collections:
    - arista.avd
    - arista.cvp

  tasks:
    - name: 'reset local folders for output'
      tags: [build, generate]
      import_role:
        name: arista.avd.build_output_folders

    - name: generate intended variables
      tags: [build, generate]
      import_role:
        name: arista.avd.eos_designs

    - name: generate device intended config and documentation
      tags: [build, generate]
      import_role:
        name: eos_cli_config_gen
