---
# local users
local_users:
  # Username with no password configured
  admin:
    privilege: 15
    role: Administrator
    sha512_password: "$6$XiiRNgJOU/Yyz4Xk$rr8JTkAVL/fgU5rm0Bx1Qt0rbl.kN4IedmTzbdDbFe/DKvQHWWFYp6Ax1j4nWOCfgj.vI69VewFpYFeXjTnwt."

  # Username with a password
  automator:
    privilege: 15
    role: network-admin
    no_password: true
    ssh_key: "AAAAB3NzaC1yc2EAAAADAQABAAABgQC7prl32xxTUtfElkOxFO6DMwS9Jdkdv4KeK9R078Le30YK+xwmgkUZBcvEhZd5ddfcoJIOrUB44agRxGBDjykt1vnWY4lDQnhN6FeE5kbDhT9jIz7LCtf7zy+TFM4+2ugmRA7BooVhFBIlQGZXI67vwtx1JmjhS50jJIlDCf9nnSDCT2RfHyZnCu+B0NID4Z28nbYSerT/CMaJU0yyZA/Vk8dkKJQni0BFvBs/7O8YJV4yhjXXsXKK0iI74dtRnxgR6hiUvmhg5WR8VZgcECu0q1Uji91nYRTWOOyEjFQQsFcRREFG6lrNdLkCnPmwwC0mLi5BFAv5QzU4JRwnb5j+nluxjeib/iVn6uKmVG40Lb1ktnK8BqducOWBgnrwZzg+brfThBhqr6SVz20GWwwmIHsOrlgGxjbJEFmCdGD3BpklKTZ7UIzPLbzt80ZHg1xxuBGh07D/nS8k9qwm7v8bGup8JJzFbhb/wLK8Ykhs2I2dIKo3kFccVR9+20m+7YU= arista@srvr2"

# dns servers.
name_servers:
  - 192.168.255.110
dns_domain: lab.local

# NTP Servers IP or DNS name, first NTP server will be preferred, and sourced from Management VRF
ntp:
  servers:
  - name: time.google.com
    preferred: true
    vrf: MGMT
    iburst: true
    local_interface: Management1

timezone: Denver

cvp_instance_ip: cvp.lab.local
cvp_ingestauth_key: 'arista'

mgmt_gateway: 192.168.255.1
mgmt_interface: Management0
mgmt_interface_vrf: MGMT
